
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"LR-Articles-Add-Delete","number":78,"title":"LR Articles Add Delete","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/78"},{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"LR-Articles-Add-Put","number":77,"title":"LR Articles Add Put","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/77"},{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"LR-Articles-Add-Get","number":76,"title":"LR Articles Added Get","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/76"},{"author":{"id":"MDQ6VXNlcjkxMzkxMTEx","is_bot":false,"login":"jamespflaging","name":"James Pflaging"},"headRefName":"James-RecommendationRequestDelete","number":75,"title":"Added DELETE for Recommendation Requests + Tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/75"},{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"LR-Articles-create-controller","number":62,"title":"LR - Articles Create Controller, Get, and Post","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/62"}]
