
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBbk9KA","is_bot":false,"login":"owenjpark","name":"Owen Park"},"headRefName":"Owen-UCSBDiningCommonsMenuItem-create-db","number":53,"title":"OP - created database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/53"},{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"LR-Articles-create-db","number":52,"title":"LR - Create database table for Articles","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/52"},{"author":{"id":"U_kgDOB09jxQ","is_bot":false,"login":"Daoyijiucsb","name":"Daoyi"},"headRefName":"Daoyi-HR-Controller-Delete","number":51,"title":"ADD Help Request Controller and Test API(DELETE)","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/51"},{"author":{"id":"U_kgDOB09jxQ","is_bot":false,"login":"Daoyijiucsb","name":"Daoyi"},"headRefName":"Daoyi-HR-Controller-Put","number":50,"title":"ADD Help Request Controller and Test API(UPDATE) ","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/50"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"zp-MenuItemReview-create-db","number":49,"title":"Add MenuItemReview Database Table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/49"},{"author":{"id":"U_kgDOB09jxQ","is_bot":false,"login":"Daoyijiucsb","name":"Daoyi"},"headRefName":"Daoyi-HR-Controller-Get","number":48,"title":"ADD Help Request Controller and Test API(GET)","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/48"},{"author":{"id":"U_kgDOBXd_vw","is_bot":false,"login":"gretchenlam","name":""},"headRefName":"Gretchen-UCSBOrganization","number":47,"title":"Add UCSBOrganization Database Table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/47"},{"author":{"id":"U_kgDOB09jxQ","is_bot":false,"login":"Daoyijiucsb","name":"Daoyi"},"headRefName":"Daoyi-HelpRequest-Controller","number":46,"title":"ADD Help Request Controller and Test API(ALL,POST)","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/46"},{"author":{"id":"U_kgDOB09jxQ","is_bot":false,"login":"Daoyijiucsb","name":"Daoyi"},"headRefName":"Daoyi-HelpRequest","number":45,"title":"Add Help Request Table ","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/45"}]
