
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjkxMzkxMTEx","is_bot":false,"login":"jamespflaging","name":"James Pflaging"},"headRefName":"James-RecommendationRequestTable","number":71,"title":"Add Recommendation Request DB Table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/71"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"zp-MenuItemReview-Controller-PUT","number":68,"title":"Add PUT (edit) endpoint for a single record in MenuItemReview table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/68"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"zp-MenuItemReview-Controller-DELETE","number":67,"title":"added DELETE endpoint for a single record in MenuItemReview table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/67"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"zp-MenuItemReview-Controller-GET","number":66,"title":"added GET (show) endpoint for a single record in MenuItemReview table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/66"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"zp-MenuItemReview-Controller","number":64,"title":"Added Menu Item Review Controller and Controller tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/64"},{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"LR-Articles-create-controller","number":62,"title":"LR - Articles Create Controller, Get, and Post","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-1/pull/62"}]
